import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { callEdgeFunction } from '../../lib/apiClient';
import { EDGE_FUNCTIONS } from '../../lib/edgeFunctions';
import { newOperationId } from '../../lib/id';
import { WEEKDAYS } from '../../lib/weekdays';
import type { HouseholdMemberWithProfile } from '../../app/HouseholdContext';

type Row={id:string;title:string;is_active:boolean;include_in_routine_line:boolean; weekdays:number[]; localTime:string; strategy:string; assignee:string};
export function CustomRoutineEditor({householdId,members,kind}:{householdId:string|null;members:HouseholdMemberWithProfile[];kind:'morning_chore'|'evening_chore'}) {
 const [rows,setRows]=useState<Row[]>([]); const [title,setTitle]=useState('');const [days,setDays]=useState<number[]>([]);const [time,setTime]=useState(kind==='morning_chore'?'07:00':'20:00');const [strategy,setStrategy]=useState('fixed');const [assignee,setAssignee]=useState('');const [line,setLine]=useState(true);const [subtaskText,setSubtaskText]=useState('');const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!householdId)return;const [defs,rules]=await Promise.all([supabase.from('task_definitions').select('id,title,is_active,include_in_routine_line').eq('household_id',householdId).eq('task_kind',kind),supabase.from('recurrence_rules').select('task_definition_id,weekday,scheduled_local_time,assignee_strategy,planned_assignee_id').eq('household_id',householdId).eq('active',true)]);if(defs.error||rules.error){setError(defs.error?.message??rules.error?.message??'読み込みに失敗しました。');return;}setRows((defs.data??[]).map(d=>{const r=(rules.data??[]).filter(x=>x.task_definition_id===d.id);return{id:d.id,title:d.title,is_active:d.is_active,include_in_routine_line:d.include_in_routine_line,weekdays:r.map(x=>x.weekday),localTime:r[0]?.scheduled_local_time?.slice(0,5)??time,strategy:r[0]?.assignee_strategy??'fixed',assignee:r[0]?.planned_assignee_id??''};}));},[householdId,kind,time]);useEffect(()=>{load();},[load]);
 const save=async(row:Row)=>{setError(null);try{await callEdgeFunction(EDGE_FUNCTIONS.editTaskDefinition,{operation_id:newOperationId(),task_definition_id:row.id,title:row.title,routine_phase:kind==='morning_chore'?'morning':'evening'});await callEdgeFunction(EDGE_FUNCTIONS.setRoutineDefinitionOptions,{operation_id:newOperationId(),task_definition_id:row.id,enabled:row.is_active,include_in_routine_line:row.include_in_routine_line});if(row.is_active)await callEdgeFunction(EDGE_FUNCTIONS.replaceRecurrenceSchedule,{operation_id:newOperationId(),replacements:[{task_definition_id:row.id,rules:row.weekdays.map(weekday=>({weekday,assignee_strategy:row.strategy,planned_assignee_user_id:row.strategy==='fixed'?row.assignee:undefined,scheduled_local_time:row.localTime}))}]});await load();}catch(e){setError(e instanceof Error?e.message:'保存に失敗しました。');}};
 const add=async()=>{if(!title.trim()||!days.length){setError('名前と曜日を入力してください。');return;}try{const subtasks=subtaskText.split(/\\n|,/).map(x=>x.trim()).filter(Boolean).map((title,sort_order)=>({title,sort_order,required:true}));const created=await callEdgeFunction<{task_definition_id:string}>(EDGE_FUNCTIONS.createTaskDefinition,{operation_id:newOperationId(),code:`${kind}_custom_${Date.now()}`,title:title.trim(),category:'household',routine_phase:kind==='morning_chore'?'morning':'evening',completion_mode:subtasks.length?'subtasks':'whole',subtasks:subtasks.length?subtasks:undefined});const row:Row={id:created.task_definition_id,title:title.trim(),is_active:true,include_in_routine_line:line,weekdays:days,localTime:time,strategy,assignee};await save(row);setTitle('');setDays([]);setSubtaskText('');}catch(e){setError(e instanceof Error?e.message:'追加に失敗しました。');}};
 const update=(id:string,p:Partial<Row>)=>setRows(xs=>xs.map(x=>x.id===id?{...x,...p}:x));const dayPicker=(selected:number[],change:(v:number[])=>void)=><div className="weekday-picker">{WEEKDAYS.map(day=><label key={day.value} className="weekday-chip"><input type="checkbox" checked={selected.includes(day.value)} onChange={()=>change(selected.includes(day.value)?selected.filter(x=>x!==day.value):[...selected,day.value])}/>{day.label}</label>)}</div>;
 const label=kind==='morning_chore'?'朝の定例家事':'夜の定例家事';return <section className="card routine-editor"><h2>{label}</h2><p className="empty-hint">追加した項目はToday・LINE・Historyに出ます。月・週やGoogle Calendarには出ません。</p>{rows.map(row=><article key={row.id} className="routine-rule"><input value={row.title} onChange={e=>update(row.id,{title:e.target.value})}/><label><input type="checkbox" checked={row.is_active} onChange={e=>update(row.id,{is_active:e.target.checked})}/>有効</label><label><input type="checkbox" checked={row.include_in_routine_line} onChange={e=>update(row.id,{include_in_routine_line:e.target.checked})}/>LINEチェックリストへ含める</label>{dayPicker(row.weekdays,v=>update(row.id,{weekdays:v}))}<input type="time" value={row.localTime} onChange={e=>update(row.id,{localTime:e.target.value})}/><select value={row.strategy} onChange={e=>update(row.id,{strategy:e.target.value})}><option value="fixed">固定担当</option><option value="dropoff_assignee">送り担当</option><option value="pickup_assignee">迎え担当</option><option value="nonpickup_adult">迎え以外</option></select>{row.strategy==='fixed'&&<select value={row.assignee} onChange={e=>update(row.id,{assignee:e.target.value})}><option value="">選択</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.profile?.display_name??m.user_id}</option>)}</select>}<button type="button" onClick={()=>save(row)}>保存</button></article>)}<div className="add-preparation"><h3>＋ 項目を追加</h3><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例: ゴミ出し"/><textarea value={subtaskText} onChange={e=>setSubtaskText(e.target.value)} placeholder="任意の子タスク（改行またはカンマ区切り）"/>{dayPicker(days,setDays)}<input type="time" value={time} onChange={e=>setTime(e.target.value)}/><select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="fixed">固定担当</option><option value="dropoff_assignee">送り担当</option><option value="pickup_assignee">迎え担当</option></select>{strategy==='fixed'&&<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">選択</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.profile?.display_name??m.user_id}</option>)}</select>}<label><input type="checkbox" checked={line} onChange={e=>setLine(e.target.checked)}/>LINEチェックリストへ含める</label><button type="button" onClick={add}>追加する</button></div>{error&&<p role="alert" className="error-text">{error}</p>}</section>;
}
