export const EVIDENCE_CLASSES = [
  'unit-domain',
  'db-rpc',
  'edge-api',
  'browser',
  'line-transport',
  'google-provider',
  'image-ocr-ai',
  'physical-iphone-manual',
  'cross-channel-concurrency',
  'whole-day-scenario',
];

export const AUTHORING_STATUSES = [
  'runnable',
  'expected-failing',
  'external-pending',
  'skeleton',
];

const q = (numbers) => numbers.map((number) => `Q${number}`);
const range = (start, end) => Array.from({ length: end - start + 1 }, (_, index) => `Q${start + index}`);

export const cf14Scenarios = [
  {
    scenarioId: 'CF14-TODAY-DAY-FLOW',
    requirementIds: q([1, 9, 13, 15, 23, 24, 35, 40, 68, 75, 87]),
    ownerLane: 'Today implementation owner + F2 verifier',
    entryBoundary: 'PWA Today route opened/revisited by the user at controlled clock times',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'browser', 'physical-iphone-manual', 'whole-day-scenario'],
    userVisibleAssertion: 'Loading/error/stale/current states and daypart ordering are visible without hiding material Today work on iPhone.',
    status: 'expected-failing',
    expectedFailureReason: 'Today implementation is owned by another lane; F1 authors the boundary harness but does not alter Today behavior.',
  },
  {
    scenarioId: 'CF14-REQUEST-LIFECYCLE',
    requirementIds: q([2, 30, 36, 41, 42, 43, 44, 45, 46, 47, 51]),
    ownerLane: 'Request implementation owner + F2 verifier',
    entryBoundary: 'User request/response through PWA and LINE command entry points',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser', 'line-transport'],
    userVisibleAssertion: 'The user sees one coherent Request lifecycle, with stale/expired attempts failing closed and accepted work joining the linked ToDo.',
    status: 'expected-failing',
    expectedFailureReason: 'Request canonicalization is converging in another lane; F1 provides lifecycle/stale/expiry fixtures without modifying business logic.',
  },
  {
    scenarioId: 'CF14-HANDOVER-SHARE',
    requirementIds: q([3, 16, 37, 38, 48, 49]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'PWA/LINE share or handover creation and acknowledgement',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser', 'line-transport'],
    userVisibleAssertion: 'Validity, acknowledgement need, household visibility and correction history are visible from the actual user entry path.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-CHECKIN-RECONCILIATION',
    requirementIds: q([5, 6, 31, 53, 54, 59, 60, 61, 63, 64, 76]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'PWA/LINE check-in and daily reconciliation entry',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser', 'line-transport', 'whole-day-scenario'],
    userVisibleAssertion: 'Bulk completion, exceptions, unknowns and next-day entry preserve the intended task facts from the user-facing flow.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-TASK-QUICK-ADD',
    requirementIds: q([8, 21, 22, 55, 56, 57, 69, 74]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'PWA Quick Add / task interaction',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser'],
    userVisibleAssertion: 'Free-text task creation, optional scheduling fields, waiting state and unassigned ownership are observable after real interaction.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-PLANNING-ASSIGNMENT',
    requirementIds: q([10, 11, 12, 50, 52, 83, 84, 85, 86]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Assignment/rule change entry and its notification/review surfaces',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser', 'line-transport', 'cross-channel-concurrency'],
    userVisibleAssertion: 'Rule scope, protected agreements, pre-arranged changes and corrections remain coherent across both channels.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-EVENT-PLANNING',
    requirementIds: q([17, 18, 19]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Event creation/review UI starting from user event-planning intent',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser'],
    userVisibleAssertion: 'Template/AI candidates remain proposals until human confirmation and no event-wide coordinator is invented.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-HISTORY-ACTUALS',
    requirementIds: q([7, 20, 28, 29, 32, 62]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'History / actuals UI after completed work and correction',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'browser'],
    userVisibleAssertion: 'Completed work, multiple performers and corrections are visible without rewriting historical facts or exposing analytics as push content.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-NOTIFICATION-SCHEDULE',
    requirementIds: q([14, 25, 26, 88]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Scheduler -> delivery intent -> user-visible LINE notification',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'line-transport', 'whole-day-scenario'],
    userVisibleAssertion: 'Morning/evening scheduled messages and exceptions arrive at the correct clock boundary without noisy pre-emptive reminders.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-LINE-DAILY-ENTRY',
    requirementIds: q([4, 39, 65, 66, 67, 72, 73, 78, 79, 80]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Actual LINE Messaging API webhook/postback and resulting reply/deep-link',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'line-transport', 'browser', 'cross-channel-concurrency'],
    userVisibleAssertion: 'LINE remains the daily operational entry, shows all own tasks, deep-links to matching PWA state, and avoids duplicate/self-return notifications.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-Q27-LINE-WEBHOOK-POSTBACK',
    requirementIds: q([27]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Actual LINE Messaging API webhook + postback into one-user test mode',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'line-transport'],
    userVisibleAssertion: 'One operator can act as both sides in the LINE test flow while all production spouse/Google/analytics side effects remain fenced.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-Q70-RAW-MULTI-INTENT',
    requirementIds: q([70]),
    ownerLane: 'LINE/Concierge implementation owner + F2 verifier',
    entryBoundary: 'Raw natural-language LINE text before candidate JSON exists',
    requiredEvidenceClasses: ['unit-domain', 'edge-api', 'line-transport'],
    userVisibleAssertion: 'One raw message containing multiple intents becomes multiple candidates shown together in one confirmation surface.',
    status: 'expected-failing',
    expectedFailureReason: 'F1 adds raw-text corpus/harness; production interpretation remains owned by its implementation lane.',
  },
  {
    scenarioId: 'CF14-Q71-RAW-AMBIGUITY',
    requirementIds: q([71]),
    ownerLane: 'LINE/Concierge implementation owner + F2 verifier',
    entryBoundary: 'Raw natural-language LINE text with only one material ambiguity',
    requiredEvidenceClasses: ['unit-domain', 'edge-api', 'line-transport'],
    userVisibleAssertion: 'Only the unresolved field is asked; already-understood content is preserved without repeated confirmation.',
    status: 'expected-failing',
    expectedFailureReason: 'F1 authors the raw-language corpus and missing-field contract; production interpretation belongs to another lane.',
  },
  {
    scenarioId: 'CF14-NAVIGATION-RETURN',
    requirementIds: q([77]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'PWA navigation from daily flow to secondary management and back',
    requiredEvidenceClasses: ['browser', 'physical-iphone-manual'],
    userVisibleAssertion: 'Management stays secondary and returning does not lose material user state or unexpectedly reset position.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-DUPLICATE-TERMINAL-GUARDS',
    requirementIds: q([81, 82]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Edge/API mutation boundary with duplicate/stale/terminal commands',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'cross-channel-concurrency'],
    userVisibleAssertion: 'Duplicate candidates are not silently merged, and non-mistake history is preserved as state rather than deleted.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-Q58-DEFERRED-DAG',
    requirementIds: q([58]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Domain/schema and user-surface audit',
    requiredEvidenceClasses: ['unit-domain'],
    userVisibleAssertion: 'No complex dependency-DAG workflow is introduced while meaningful daily grouping remains available.',
    status: 'runnable',
  },
  {
    scenarioId: 'CF14-SHOPPING-ACTION',
    requirementIds: q([33]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'PWA shopping action completion',
    requiredEvidenceClasses: ['unit-domain', 'db-rpc', 'edge-api', 'browser'],
    userVisibleAssertion: 'Shopping completion is recorded as one household action rather than one achievement per product.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-Q107-Q109-SHOPPING-INTERACTION',
    requirementIds: range(107, 109),
    ownerLane: 'F1 authoring + F2 verifier',
    entryBoundary: 'Rendered PWA anyone-owner page with user button interaction',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'browser'],
    userVisibleAssertion: 'Unclaimed items can be claimed, another claimant can be intentionally taken over, and the current claimant releases only by explicit action.',
    status: 'runnable',
  },
  {
    scenarioId: 'CF14-NURSERY-ACTUAL-INPUT',
    requirementIds: range(89, 106),
    ownerLane: 'Nursery implementation owner + F2 verifier',
    entryBoundary: 'Actual image bytes received at LINE/image intake before OCR or AI candidate construction',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'line-transport', 'image-ocr-ai', 'browser'],
    userVisibleAssertion: 'Actual notice images pass classification/OCR/AI with provenance, then one review surface controls confirmation before household data changes.',
    status: 'expected-failing',
    expectedFailureReason: 'F1 authors image-byte/provenance evidence harness; final OCR/AI/provider execution requires converged implementation and controlled credentials.',
  },
  {
    scenarioId: 'CF14-GOOGLE-BASELINE',
    requirementIds: q([34]),
    ownerLane: 'Google implementation owner + F2 verifier',
    entryBoundary: 'Controlled Google Calendar provider response before Family Ops projection',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'google-provider', 'browser'],
    userVisibleAssertion: 'Calendar events are the primary projected Google content and ToDo projection remains optional.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-Q110-Q112-GOOGLE-PROVIDER',
    requirementIds: range(110, 112),
    ownerLane: 'Google implementation owner + F2 verifier',
    entryBoundary: 'Controlled Google Calendar provider change/delete/duplicate response',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'google-provider', 'browser'],
    userVisibleAssertion: 'Provider changes produce human-reviewable diffs; deletion and duplicate candidates never silently overwrite or merge protected Family Ops values.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-LINE-PWA-CONCURRENT-RACE',
    requirementIds: q([78, 79, 81, 84, 108, 109]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Concurrent actual LINE transport and PWA Edge/API commands against the same aggregate revision',
    requiredEvidenceClasses: ['db-rpc', 'edge-api', 'browser', 'line-transport', 'cross-channel-concurrency'],
    userVisibleAssertion: 'Both channels converge on one canonical result and a stale loser fails visibly rather than silently overwriting the winner.',
    status: 'external-pending',
  },
  {
    scenarioId: 'CF14-WHOLE-DAY-ORCHESTRATION',
    requirementIds: q([1, 5, 9, 14, 23, 25, 26, 39, 40, 63, 75, 87, 88]),
    ownerLane: 'F2 verifier',
    entryBoundary: 'Clock-controlled full-day sequence across scheduled LINE, PWA Today, check-in and cross-channel updates',
    requiredEvidenceClasses: ['browser', 'line-transport', 'physical-iphone-manual', 'cross-channel-concurrency', 'whole-day-scenario'],
    userVisibleAssertion: 'A family can move from morning brief through daytime changes to evening reconciliation without lost state, duplicate noise or hidden work.',
    status: 'skeleton',
    expectedFailureReason: 'F1 provides orchestration structure only; final execution waits for all implementation lanes to converge on one exact HEAD.',
  },
];
