import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
const BUCKET='artifact-handoff', HARD_MAX=50*1024*1024, URL_TTL=900
const out=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})
function key(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{const p=JSON.parse(modern);if(p?.default)return String(p.default)}catch{}}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!legacy)throw new Error('server secret unavailable');return legacy}
async function sha(b:Uint8Array){const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req)=>{try{
 const url=new URL(req.url), action=url.searchParams.get('action')??((req.method==='PUT'||req.method==='POST')?'upload':'status')
 const token=(req.headers.get('x-handoff-token')??'').trim();if(!/^[A-Za-z0-9_-]{32,200}$/.test(token))return out({error:'missing_or_invalid_handoff_token'},401)
 const db=createClient(Deno.env.get('SUPABASE_URL')!,key(),{auth:{persistSession:false,autoRefreshToken:false}}), tokenSha=await sha(new TextEncoder().encode(token))
 const {data:t,error:te}=await db.from('artifact_handoff_transfers').select('*').eq('token_sha256',tokenSha).maybeSingle();if(te)return out({error:'transfer_lookup_failed',detail:te.message},500);if(!t)return out({error:'invalid_handoff_token'},403)
 const {data:ns,error:ne}=await db.from('artifact_handoff_namespaces').select('enabled,max_bytes').eq('app_slug',t.app_slug).maybeSingle();if(ne||!ns)return out({error:'namespace_lookup_failed'},500);if(!ns.enabled)return out({error:'namespace_disabled'},403)
 if(Date.now()>new Date(t.expires_at).getTime()){if(!['consumed','deleted','expired'].includes(t.status))await db.from('artifact_handoff_transfers').update({status:'expired'}).eq('id',t.id);return out({error:'transfer_expired',transferId:t.id},410)}
 if(action==='status'&&req.method==='GET')return out({transferId:t.id,app:t.app_slug,workItem:t.work_item,filename:t.filename,storagePath:t.storage_path,expectedSha256:t.expected_sha256,expectedBytes:t.expected_bytes,actualSha256:t.actual_sha256,actualBytes:t.actual_bytes,status:t.status,expiresAt:t.expires_at})
 if(action==='upload'&&(req.method==='PUT'||req.method==='POST')){
  if(['verified','consumed','deleted'].includes(t.status))return out({error:'transfer_not_uploadable',status:t.status},409)
  const max=Math.min(Number(ns.max_bytes),HARD_MAX), hinted=Number(req.headers.get('content-length')??'0');if(Number.isFinite(hinted)&&hinted>max)return out({error:'payload_too_large',maxBytes:max},413)
  await db.from('artifact_handoff_transfers').update({status:'uploading',error:null}).eq('id',t.id)
  const b=new Uint8Array(await req.arrayBuffer());if(!b.length)return out({error:'empty_payload'},400);if(b.length>max)return out({error:'payload_too_large',actualBytes:b.length,maxBytes:max},413)
  if(t.expected_bytes!=null&&Number(t.expected_bytes)!==b.length){await db.from('artifact_handoff_transfers').update({status:'error',actual_bytes:b.length,error:'byte length mismatch'}).eq('id',t.id);return out({error:'byte_length_mismatch',expectedBytes:Number(t.expected_bytes),actualBytes:b.length},422)}
  const pre=await sha(b);if(pre!==t.expected_sha256){await db.from('artifact_handoff_transfers').update({status:'error',actual_sha256:pre,actual_bytes:b.length,error:'sha256 mismatch before storage'}).eq('id',t.id);return out({error:'sha256_mismatch_pre_storage',expectedSha256:t.expected_sha256,actualSha256:pre,actualBytes:b.length},422)}
  const {error:ue}=await db.storage.from(BUCKET).upload(t.storage_path,b,{contentType:t.content_type,cacheControl:'0',upsert:true});if(ue){await db.from('artifact_handoff_transfers').update({status:'error',error:`storage upload: ${ue.message}`}).eq('id',t.id);return out({error:'storage_upload_failed',detail:ue.message},500)}
  const {data:d,error:de}=await db.storage.from(BUCKET).download(t.storage_path);if(de||!d)return out({error:'storage_redownload_failed',detail:de?.message},500)
  const rb=new Uint8Array(await d.arrayBuffer()), post=await sha(rb);if(rb.length!==b.length||post!==pre){await db.from('artifact_handoff_transfers').update({status:'error',actual_sha256:post,actual_bytes:rb.length,error:'storage roundtrip mismatch'}).eq('id',t.id);return out({error:'storage_roundtrip_mismatch',preSha:pre,postSha:post,uploadedBytes:b.length,downloadedBytes:rb.length},500)}
  const stamp=new Date().toISOString();const {error:ve}=await db.from('artifact_handoff_transfers').update({status:'verified',actual_sha256:post,actual_bytes:rb.length,uploaded_at:stamp,verified_at:stamp,error:null}).eq('id',t.id);if(ve)return out({error:'verification_record_failed',detail:ve.message},500)
  return out({ok:true,status:'verified',transferId:t.id,app:t.app_slug,workItem:t.work_item,storagePath:t.storage_path,bytes:rb.length,sha256:post,storageRoundTripVerified:true})
 }
 if(action==='download-url'&&req.method==='POST'){if(!['verified','consumed'].includes(t.status))return out({error:'artifact_not_verified',status:t.status},409);const {data,error}=await db.storage.from(BUCKET).createSignedUrl(t.storage_path,URL_TTL,{download:t.filename});if(error||!data?.signedUrl)return out({error:'signed_url_failed',detail:error?.message},500);return out({transferId:t.id,signedUrl:data.signedUrl,expiresInSeconds:URL_TTL,filename:t.filename,sha256:t.actual_sha256,bytes:t.actual_bytes})}
 if(action==='mark-consumed'&&req.method==='POST'){if(t.status!=='verified')return out({error:'artifact_not_verified',status:t.status},409);const stamp=new Date().toISOString(),{error}=await db.from('artifact_handoff_transfers').update({status:'consumed',consumed_at:stamp}).eq('id',t.id);if(error)return out({error:'consume_update_failed',detail:error.message},500);return out({ok:true,transferId:t.id,status:'consumed'})}
 if(action==='delete'&&(req.method==='DELETE'||req.method==='POST')){if(t.status!=='consumed')return out({error:'artifact_must_be_consumed_before_delete',status:t.status},409);if(req.headers.get('x-confirm-delete')!==t.id)return out({error:'delete_confirmation_mismatch'},400);const {error:re}=await db.storage.from(BUCKET).remove([t.storage_path]);if(re)return out({error:'storage_delete_failed',detail:re.message},500);const stamp=new Date().toISOString();await db.from('artifact_handoff_transfers').update({status:'deleted',deleted_at:stamp}).eq('id',t.id);return out({ok:true,transferId:t.id,status:'deleted'})}
 return out({error:'unsupported_action_or_method',action,method:req.method},405)
}catch(e){return out({error:'internal_error',detail:String(e)},500)}})
