import { EDGE_FUNCTIONS, type EdgeFunctionName } from './edgeFunctions';

export type RequestPolicyKind = 'read' | 'proposal' | 'mutation';

export const REQUEST_POLICY = {
  createHousehold: 'mutation',
  createHouseholdInvite: 'mutation',
  joinHousehold: 'mutation',
  configureEveningRoutines: 'mutation',
  configureDropoffPickup: 'mutation',
  createTask: 'mutation',
  editTask: 'mutation',
  commitConciergeDuplicate: 'mutation',
  cancelTask: 'mutation',
  completeTask: 'mutation',
  reopenTask: 'mutation',
  recordUnplannedActual: 'mutation',
  addTaskCompletionEvidence: 'mutation',
  setTaskWaiting: 'mutation',
  correctTaskActual: 'mutation',
  changeTaskAssignment: 'mutation',
  setSubtaskCompletion: 'mutation',
  createTaskDefinition: 'mutation',
  editTaskDefinition: 'mutation',
  updateTaskCategories: 'mutation',
  updateHouseholdTerminology: 'mutation',
  deactivateTaskDefinition: 'mutation',
  sendRequest: 'mutation',
  acceptRequest: 'mutation',
  declineRequest: 'mutation',
  respondRequest: 'mutation',
  negotiateRequest: 'mutation',
  cancelRequest: 'mutation',
  startRequestFollowup: 'mutation',
  proposeAiDraft: 'proposal',
  proposeConciergeCandidates: 'proposal',
  proposeEventPlan: 'proposal',
  confirmEventPlan: 'mutation',
  addShoppingItem: 'mutation',
  assignShoppingItem: 'mutation',
  orderShoppingItem: 'mutation',
  purchaseShoppingItem: 'mutation',
  arriveShoppingItem: 'mutation',
  cancelShoppingItem: 'mutation',
  claimShoppingItem: 'mutation',
  reopenShoppingItem: 'mutation',
  createHandover: 'mutation',
  markHandoverRead: 'mutation',
  markNotificationRead: 'mutation',
  updateNotificationPreferences: 'mutation',
  createLineLinkToken: 'mutation',
  updateRoutineSchedule: 'mutation',
  changeRecurrence: 'mutation',
  deactivateRecurrence: 'mutation',
  reassignTaskOnce: 'mutation',
  confirmRequestDraft: 'mutation',
  createAssignmentChangeRequest: 'mutation',
  acceptAssignmentChangeRequest: 'mutation',
  getRoutineSession: 'read',
  completeRoutineSession: 'mutation',
  routineSessionItemAction: 'mutation',
  reconcileRoutineSession: 'mutation',
  getCurrentRoutineSessions: 'read',
  listPendingActions: 'read',
  confirmPendingAction: 'mutation',
  cancelPendingAction: 'mutation',
  updatePendingAction: 'mutation',
  getTodaySchedule: 'read',
  getWeekSchedule: 'read',
  googleCalendarOauthStart: 'mutation',
  ensureCalendarFresh: 'mutation',
  completeOnboardingStep: 'mutation',
  replaceRecurrenceSchedule: 'mutation',
  setRoutineDefinitionOptions: 'mutation',
  replaceRoutineSubtasks: 'mutation',
  setFamilyCalendarTarget: 'mutation',
  setFamilyRole: 'mutation',
  testSimulation: 'mutation',
  transportSchedule: 'mutation',
  getNurseryReview: 'read',
  listNurseryReviews: 'read',
  resolveNurseryAmbiguity: 'mutation',
  confirmNurseryReview: 'mutation',
  deleteNurserySourceImage: 'mutation',
  listGoogleEventReviews: 'read',
  resolveGoogleEventReview: 'mutation',
} satisfies Record<keyof typeof EDGE_FUNCTIONS, RequestPolicyKind>;

const REQUEST_POLICY_BY_FUNCTION = Object.fromEntries(
  (Object.keys(EDGE_FUNCTIONS) as Array<keyof typeof EDGE_FUNCTIONS>).map((key) => [
    EDGE_FUNCTIONS[key],
    REQUEST_POLICY[key],
  ]),
) as Record<EdgeFunctionName, RequestPolicyKind>;

export const REQUEST_DEADLINES_MS: Record<RequestPolicyKind | 'auth', number> = {
  auth: 12_000,
  read: 12_000,
  mutation: 30_000,
  proposal: 45_000,
};

export function requestPolicyFor(name: EdgeFunctionName): RequestPolicyKind {
  return REQUEST_POLICY_BY_FUNCTION[name];
}
